#!/bin/zsh

HISTFILE=$ZDOTDIR/.zsh_history

SAVEHIST=100_000 # Max entries stored in the history file.
HISTSIZE=120_000 # Max entries stored in memory.

setopt EXTENDED_HISTORY       # Timestamp history file entries.
setopt HIST_IGNORE_DUPS       # Ignore consecutive dups.
setopt HIST_EXPIRE_DUPS_FIRST # Remove dup entries first when trimming history.
setopt HIST_IGNORE_SPACE      # Don't add commands beginning with a space to the history file.
setopt HIST_VERIFY            # Move commands with history expansion into the buffer for review before executing.
setopt SHARE_HISTORY          # Sync history across sessions.
setopt NO_CLOBBER             # Don't let > overwrite an existing file. Use >! instead.
setopt INTERACTIVE_COMMENTS   # Allow comments in interactive shell.
setopt AUTO_CD                # Auto cd with just a dir name.

alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -Alh'

alias -- -='cd -'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # Case insensitive tab completion.

local znap=$XDG_DATA_HOME/zsh-snap/znap.zsh
local znap_repos_dir=$XDG_DATA_HOME/zsh-snap-repos

[[ -r $znap ]] || git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git $znap:h

. $znap # Runs compinit for you.

zstyle ':znap:*' repos-dir $znap_repos_dir

znap prompt sindresorhus/pure
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
